---
title: "Reading and preprocessing tidal data"
author: "katerobsau"
date: "2019-08-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r load packages, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(DiagrammeR)
```

```{r tidal pacakge read, echo = FALSE, warning = FALSE, message = FALSE}
package_dir = "code/tidalHelpers"
list.files(package_dir)
install.packages(pkgs = "code/tidalHelpers", repos = NULL, type = "source")
library(tidalHelpers)
```

```{r install funGraphs package, echo = FALSE, warning = FALSE, message = FALSE}
bool_install = "funGraphs" %in% rownames(installed.packages())
if(bool_install == FALSE){
  devtools::install_github("kcf-jackson/funGraphs")
}
library(funGraphs)
```

## General Background

* Where is the data stored
* What is the data - run with which model
* How did we get the data (save Kiri's script)

## Global Variables

```{r variables, echo = FALSE, warning = FALSE, message = FALSE}
tidalHelpers::utils_init()
```

## Code 

Code to preprocess the tidal data is stored in the associated sub-directory "code/tidalHelpers".

See files:
```{r code outline, eval = FALSE}
write_ensemble_summary_to_file.R
save_ensemble_summaries.R
save_obs_summaries.R
```

An overview of the codes workflow and connections is given below.
```{r show package graph, echo = FALSE}
r_file_dir = paste0(package_dir, "/R/", sep = "") 
pkg_graph <- funGraphs::build_graph_from_dir(dir0 = r_file_dir)
node_labels <- paste0(pkg_graph$nodes$label, collapse = ";") 
edge_dirs <- pkg_graph$edges %>% 
  apply(1, function(row){paste(row[1], row[2], sep = " -> ")}) %>%
  str_c(collapse = "\n")
graph_str <- str_c(c("digraph flowchart {",  node_labels,
                   "\n", edge_dirs, "}"), collapse = "")
grViz(graph_str)
```

Show what the data looks like too!!
